// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFriendFieldNames          = builder.RawFieldNames(&UserFriend{})
	userFriendRows                = strings.Join(userFriendFieldNames, ",")
	userFriendRowsExpectAutoSet   = strings.Join(stringx.Remove(userFriendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userFriendRowsWithPlaceHolder = strings.Join(stringx.Remove(userFriendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUsercenterUserFriendIdPrefix             = "cache:usercenter:userFriend:id:"
	cacheUsercenterUserFriendUserIdFriendIdPrefix = "cache:usercenter:userFriend:userId:friendId:"
)

type (
	userFriendModel interface {
		Insert(ctx context.Context, data *UserFriend) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserFriend, error)
		FindOneByUserIdFriendId(ctx context.Context, userId int64, friendId int64) (*UserFriend, error)
		Update(ctx context.Context, data *UserFriend) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserFriendModel struct {
		sqlc.CachedConn
		table string
	}

	UserFriend struct {
		Id        int64        `db:"id"`
		UserId    int64        `db:"user_id"`
		FriendId  int64        `db:"friend_id"`
		CreatedAt time.Time    `db:"created_at"`
		DeletedAt sql.NullTime `db:"deleted_at"`
	}
)

func newUserFriendModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserFriendModel {
	return &defaultUserFriendModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_friend`",
	}
}

func (m *defaultUserFriendModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	usercenterUserFriendIdKey := fmt.Sprintf("%s%v", cacheUsercenterUserFriendIdPrefix, id)
	usercenterUserFriendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheUsercenterUserFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, usercenterUserFriendIdKey, usercenterUserFriendUserIdFriendIdKey)
	return err
}

func (m *defaultUserFriendModel) FindOne(ctx context.Context, id int64) (*UserFriend, error) {
	usercenterUserFriendIdKey := fmt.Sprintf("%s%v", cacheUsercenterUserFriendIdPrefix, id)
	var resp UserFriend
	err := m.QueryRowCtx(ctx, &resp, usercenterUserFriendIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFriendRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFriendModel) FindOneByUserIdFriendId(ctx context.Context, userId int64, friendId int64) (*UserFriend, error) {
	usercenterUserFriendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheUsercenterUserFriendUserIdFriendIdPrefix, userId, friendId)
	var resp UserFriend
	err := m.QueryRowIndexCtx(ctx, &resp, usercenterUserFriendUserIdFriendIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? limit 1", userFriendRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, friendId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFriendModel) Insert(ctx context.Context, data *UserFriend) (sql.Result, error) {
	usercenterUserFriendIdKey := fmt.Sprintf("%s%v", cacheUsercenterUserFriendIdPrefix, data.Id)
	usercenterUserFriendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheUsercenterUserFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userFriendRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.DeletedAt)
	}, usercenterUserFriendIdKey, usercenterUserFriendUserIdFriendIdKey)
	return ret, err
}

func (m *defaultUserFriendModel) Update(ctx context.Context, newData *UserFriend) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	usercenterUserFriendIdKey := fmt.Sprintf("%s%v", cacheUsercenterUserFriendIdPrefix, data.Id)
	usercenterUserFriendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheUsercenterUserFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userFriendRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FriendId, newData.DeletedAt, newData.Id)
	}, usercenterUserFriendIdKey, usercenterUserFriendUserIdFriendIdKey)
	return err
}

func (m *defaultUserFriendModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUsercenterUserFriendIdPrefix, primary)
}

func (m *defaultUserFriendModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFriendRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserFriendModel) tableName() string {
	return m.table
}
