version: '3'
services:
  redis-0:
    image: redis:6.2.5
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --cluster-announce-ip redis-0 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "6379:6379"
      - "16379:16379"
    networks:
      - redis-cluster

  redis-1:
    image: redis:6.2.5
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --cluster-announce-ip redis-1 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "6380:6379"
      - "16380:16379"
    networks:
      - redis-cluster
    
  # 为其他节点重复上述配置，改变端口号和服务名称

networks:
  redis-cluster:
    driver: bridge
