// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"zero-chat/app/chat/cmd/rpc/internal/logic"
	"zero-chat/app/chat/cmd/rpc/internal/svc"
	"zero-chat/app/chat/cmd/rpc/pb"
)

type TableServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTableServiceServer
}

func NewTableServiceServer(svcCtx *svc.ServiceContext) *TableServiceServer {
	return &TableServiceServer{
		svcCtx: svcCtx,
	}
}

// store table
func (s *TableServiceServer) StoreAddItem(ctx context.Context, in *pb.StoreAddItemReq) (*pb.StoreAddItemResp, error) {
	l := logic.NewStoreAddItemLogic(ctx, s.svcCtx)
	return l.StoreAddItem(in)
}

func (s *TableServiceServer) GetStoreItemsBySlice(ctx context.Context, in *pb.GetStoreItemsBySliceReq) (*pb.GetStoreItemsBySliceResp, error) {
	l := logic.NewGetStoreItemsBySliceLogic(ctx, s.svcCtx)
	return l.GetStoreItemsBySlice(in)
}

// sync table
func (s *TableServiceServer) SyncAddItem(ctx context.Context, in *pb.SyncAddItemReq) (*pb.SyncAddItemResp, error) {
	l := logic.NewSyncAddItemLogic(ctx, s.svcCtx)
	return l.SyncAddItem(in)
}

func (s *TableServiceServer) SyncGetUnreadItems(ctx context.Context, in *pb.SyncGetUnreadItemsReq) (*pb.SyncGetUnreadItemsResp, error) {
	l := logic.NewSyncGetUnreadItemsLogic(ctx, s.svcCtx)
	return l.SyncGetUnreadItems(in)
}
