// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"zero-chat/app/chat/cmd/rpc/internal/logic"
	"zero-chat/app/chat/cmd/rpc/internal/svc"
	"zero-chat/app/chat/cmd/rpc/pb"
)

type TableServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTableServiceServer
}

func NewTableServiceServer(svcCtx *svc.ServiceContext) *TableServiceServer {
	return &TableServiceServer{
		svcCtx: svcCtx,
	}
}

// has been depricated
func (s *TableServiceServer) StoreAddItem(ctx context.Context, in *pb.StoreAddItemReq) (*pb.StoreAddItemResp, error) {
	l := logic.NewStoreAddItemLogic(ctx, s.svcCtx)
	return l.StoreAddItem(in)
}

func (s *TableServiceServer) SyncAddItem(ctx context.Context, in *pb.SyncAddItemReq) (*pb.SyncAddItemResp, error) {
	l := logic.NewSyncAddItemLogic(ctx, s.svcCtx)
	return l.SyncAddItem(in)
}

func (s *TableServiceServer) Send(ctx context.Context, in *pb.SendReq) (*pb.SendResp, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}

func (s *TableServiceServer) GetSyncMessage(ctx context.Context, in *pb.GetSyncMessageReq) (*pb.GetSyncMessageResp, error) {
	l := logic.NewGetSyncMessageLogic(ctx, s.svcCtx)
	return l.GetSyncMessage(in)
}

func (s *TableServiceServer) GetHistoryMessage(ctx context.Context, in *pb.GetHistoryMessageReq) (*pb.GetHistoryMessageResp, error) {
	l := logic.NewGetHistoryMessageLogic(ctx, s.svcCtx)
	return l.GetHistoryMessage(in)
}

func (s *TableServiceServer) SearchHistoryMEssage(ctx context.Context, in *pb.SearchHistoryMessageReq) (*pb.SearchHistoryMessageResp, error) {
	l := logic.NewSearchHistoryMEssageLogic(ctx, s.svcCtx)
	return l.SearchHistoryMEssage(in)
}
