// Code generated by goctl. DO NOT EDIT.
package types

type EmailLoginReq struct {
	Email   string `json:"email"`
	Captcha string `json:"captcha"`
}

type FriendIdReq struct {
	Id int64 `path:"id"`
}

type FriendSearchReq struct {
	Phone    string `json:"phone"`
	Username string `json:"username"`
}

type FriendSearchResp struct {
	Users []User `json:"users"`
}

type FriendsResp struct {
	Users []User `json:"users"`
}

type Group struct {
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	Avatar    string `json:"avatar"`
	CreatorId int64  `json:"creator_id"`
}

type GroupCreateReq struct {
	GroupInfo Group `json:"group_info"`
}

type GroupId struct {
	Id int64 `json:"id"`
}

type GroupQuitReq struct {
	GroupId int64 `json:"group_id"`
	HeirId  int64 `json:"heir_id"`
}

type GroupResp struct {
	Group GroupWithId `json:"group"`
}

type GroupUpdateReq struct {
	Group GroupWithId `json:"group"`
}

type GroupWithId struct {
	Group
	Id int64 `json:"id"`
}

type IdReq struct {
	Id int64 `json:"id"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type Null struct {
}

type PhoneLoginReq struct {
	Phone    string `json:"Phone"`
	Password string `json:"password"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Sex      int8   `json:"sex"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type User struct {
	Id       int64  `json:"id"`
	Phone    string `json:"phone"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Status   string `json:"status"`
	Desc     string `json:"desc"`
	Email    string `json:"email"`
}

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserInfoResp struct {
	UserInfo User `json:"user_info"`
}

type UserUpdateReq struct {
	UserUpdate User `json:"user_update"`
}

type UserUpdateResp struct {
	UserUpdate User `json:"user_update"`
}
